import type { WeeklySubmissionDTO } from '@/types'

export interface AIProvider {
  generateSummary(submission: Partial<WeeklySubmissionDTO>, towerName: string): Promise<string>
}

class StubAIProvider implements AIProvider {
  async generateSummary(submission: Partial<WeeklySubmissionDTO>, towerName: string): Promise<string> {
    const rag = submission.ragStatus ?? 'AMBER'
    const score = submission.totalScore ?? 0
    return `[AI STUB] KT Status for ${towerName}: Overall health is ${rag} with a score of ${score}/100. ` +
      `Progress is ${submission.progressScore ?? 0}/100, coverage ${submission.coverageScore ?? 0}/100, ` +
      `confidence ${submission.confidenceScore ?? 0}/100. ` +
      `Key narrative: ${submission.narrative ?? 'No narrative provided.'} ` +
      `This summary was generated by the stub AI provider. Set AZURE_OPENAI_KEY to enable real summaries.`
  }
}

class AzureOpenAIProvider implements AIProvider {
  private apiKey: string
  private endpoint: string
  private deploymentName: string

  constructor() {
    this.apiKey = process.env.AZURE_OPENAI_KEY!
    this.endpoint = process.env.AZURE_OPENAI_ENDPOINT!
    this.deploymentName = process.env.AZURE_OPENAI_DEPLOYMENT ?? 'gpt-4o'
  }

  async generateSummary(submission: Partial<WeeklySubmissionDTO>, towerName: string): Promise<string> {
    const prompt = `You are a KT (Knowledge Transfer) programme manager writing an executive summary.
Tower: ${towerName}
Week Ending: ${submission.weekEnding}
Org: ${submission.org}
RAG Status: ${submission.ragStatus}
Total Score: ${submission.totalScore}/100
- Progress: ${submission.progressScore}/100
- Coverage: ${submission.coverageScore}/100
- Confidence: ${submission.confidenceScore}/100
- Operational: ${submission.operationalScore}/100
- Quality: ${submission.qualityScore}/100
Narrative: ${submission.narrative ?? 'None'}
Risks: ${JSON.stringify(submission.risks ?? [])}
Blockers: ${JSON.stringify(submission.blockers ?? [])}

Write a concise 2-3 sentence executive summary highlighting the health status, key risks, and recommended actions. Be factual and direct.`

    const url = `${this.endpoint}/openai/deployments/${this.deploymentName}/chat/completions?api-version=2024-02-15-preview`
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'api-key': this.apiKey,
      },
      body: JSON.stringify({
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.3,
        max_tokens: 300,
      }),
    })

    if (!response.ok) {
      throw new Error(`Azure OpenAI error: ${response.status}`)
    }

    const data = await response.json()
    return data.choices?.[0]?.message?.content ?? 'Summary unavailable.'
  }
}

export function getAIProvider(): AIProvider {
  if (process.env.AZURE_OPENAI_KEY && process.env.AZURE_OPENAI_ENDPOINT) {
    return new AzureOpenAIProvider()
  }
  return new StubAIProvider()
}
