// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/dashboard/executive" | "/dashboard/tower/[towerId]" | "/login" | "/submissions/compare" | "/submissions/new"
type AppRouteHandlerRoutes = "/api/actions" | "/api/actions/[id]" | "/api/admin/towers" | "/api/admin/towers/[id]" | "/api/admin/users" | "/api/admin/weights" | "/api/ai/summarise" | "/api/ai/summarise/[id]/approve" | "/api/audit" | "/api/auth/login" | "/api/auth/logout" | "/api/dashboard/executive" | "/api/dashboard/tower/[id]" | "/api/pulse" | "/api/submissions" | "/api/submissions/compare" | "/api/towers" | "/api/towers/[id]" | "/api/towers/[id]/tracks"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/actions": {}
  "/api/actions/[id]": { "id": string; }
  "/api/admin/towers": {}
  "/api/admin/towers/[id]": { "id": string; }
  "/api/admin/users": {}
  "/api/admin/weights": {}
  "/api/ai/summarise": {}
  "/api/ai/summarise/[id]/approve": { "id": string; }
  "/api/audit": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/dashboard/executive": {}
  "/api/dashboard/tower/[id]": { "id": string; }
  "/api/pulse": {}
  "/api/submissions": {}
  "/api/submissions/compare": {}
  "/api/towers": {}
  "/api/towers/[id]": { "id": string; }
  "/api/towers/[id]/tracks": { "id": string; }
  "/dashboard/executive": {}
  "/dashboard/tower/[towerId]": { "towerId": string; }
  "/login": {}
  "/submissions/compare": {}
  "/submissions/new": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
