// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/executive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/executive">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/executive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/tower/[towerId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tower/[towerId]">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/tower/[towerId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/submissions/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/submissions/compare">> = Specific
  const handler = {} as typeof import("../../../src/app/submissions/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/submissions/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/submissions/new">> = Specific
  const handler = {} as typeof import("../../../src/app/submissions/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/actions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/actions/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/actions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/actions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/towers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/towers/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/towers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/towers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/towers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/towers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/weights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/weights">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/weights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/summarise/[id]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/summarise/[id]/approve">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/summarise/[id]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/summarise/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/summarise">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/summarise/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/executive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/executive">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/executive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/tower/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/tower/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/tower/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/pulse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pulse">> = Specific
  const handler = {} as typeof import("../../../src/app/api/pulse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/submissions/compare/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submissions/compare">> = Specific
  const handler = {} as typeof import("../../../src/app/api/submissions/compare/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/submissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submissions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/submissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/towers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/towers/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/towers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/towers/[id]/tracks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/towers/[id]/tracks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/towers/[id]/tracks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/towers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/towers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/towers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
